// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	omdb "github.com/rifannurmuhammad/02-movie-service/service/omdb"
	mock "github.com/stretchr/testify/mock"
)

// Omdb is an autogenerated mock type for the Omdb type
type Omdb struct {
	mock.Mock
}

// Find provides a mock function with given fields: search, page
func (_m *Omdb) Find(search string, page int) (omdb.ResponseOmdb, error) {
	ret := _m.Called(search, page)

	var r0 omdb.ResponseOmdb
	if rf, ok := ret.Get(0).(func(string, int) omdb.ResponseOmdb); ok {
		r0 = rf(search, page)
	} else {
		r0 = ret.Get(0).(omdb.ResponseOmdb)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(search, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDetail provides a mock function with given fields: id
func (_m *Omdb) FindDetail(id string) (omdb.ResponseDetailOmdb, error) {
	ret := _m.Called(id)

	var r0 omdb.ResponseDetailOmdb
	if rf, ok := ret.Get(0).(func(string) omdb.ResponseDetailOmdb); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(omdb.ResponseDetailOmdb)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
